# Generated by Django 3.1.3 on 2020-11-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sruthi_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(max_length=23)),
                ('input1', models.CharField(max_length=45)),
            ],
        ),
    ]
