# Generated by Django 3.1.3 on 2020-11-07 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sruthi_1',
            old_name='input',
            new_name='input11',
        ),
    ]
