# Generated by Django 3.1.3 on 2020-11-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_auto_20201107_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='sruthi_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input2', models.CharField(max_length=67)),
                ('input3', models.CharField(max_length=90)),
            ],
        ),
    ]
